# -*- coding: utf-8 -*-
"""array-sum-elements.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UfR6kfublVHIa9CU9nXoCTB2I9rQJzMY
"""

#soma de elementos dentro de um array
import random
n = int(input())
ar = [0] * n
sum = 0
for i in range(n):
  ar[i] = random.randint(0,9)
  print(ar)
for l in range(n):
  sum += ar[l]
  print(sum)

