# -*- coding: utf-8 -*-
"""csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EKMBSuLcntWpFR2laG737dnJyAi_otqs
"""

from google.colab import files
arquivos = files.upload()

import io
import pandas as pd

df = pd.read_csv(io.BytesIO(arquivos["pokemon.csv"]))

df

#Ordenar por nome
#ascending para ordenar descrescent6e ouy crescente 
df.sort_values(by ="Nome", ascending=False)

#Ord por ataque descescente
#inplace para alterar os  valores originais
df.sort_values(by =["Ataque" , "Defesa"], ascending=[False,True], inplace = True)
print(df)

#query para consultar e filtrar por parametros
#query é uma busca 
df.query("120 <= PS <= 130")

#para consultar quando é uma String
#usar `nome da coluna` 'valor da linha da coluna'
df.query("`Tipo 1` == 'Água' or `Tipo 2` == 'Água'")

#médias de valores
df.mean()

print(df.max())
print("==========")
print(df.min())
print("==========")
print(df.count()) #para incidencia de valores
print("==========")

df["Ataque"].max()

df["Lendário"].value_counts()

#calcular, por exemplo , a media de um det grupo de valores
#media dos ataques do tipo 1 
#groupby agrupar os valores
df.groupby("Tipo 1")["Ataque"].mean()

#max() e # min() para maximo do valor ou minimo
df.query("Lendário == True")["Ataque"].max()