# -*- coding: utf-8 -*-
"""estatistica.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EuFRPamae4Czv2IWT5WWc8c4ovECHmJu
"""

import numpy as np

a= [5,6,6,6,6,7]
b= [1,3,6,6,10,10]

#mediana
print('Media de a: ' + str(np.mean(a)))
print('Media de b: ' + str(np.mean(b)))

#variancia
print("Variancia de a: " + str(np.var(a)))
print("Variancia de b: " + str(np.var(b)))

#desvio padrao
print("Desvio padrao de a: " + str(np.std(a)))
print("Desvio padrao de b: " + str(np.std(b)))

#percentil
#25% = 25°percentil, #50% = 50°percentil, #75% = 75°percentil
notas = [1,1,1,2,2,3,3,9,10,10,10,10]
print(np.percentile(notas, q=25))
print(np.percentile(notas, q=50))
print(np.percentile(notas, q=75))

from google.colab import files
arquivos = files.upload()

import pandas as pd
import io
df = pd.read_csv(io.BytesIO(arquivos["tuition_cost.csv"]))

df["in_state_tuition"].median()

df["in_state_tuition"].mean()

print(np.percentile(df["in_state_tuition"], q=25))
print(np.percentile(df["in_state_tuition"], q=50))
print(np.percentile(df["in_state_tuition"], q=75))

#amplitude= max - min
df["in_state_tuition"].max() - df["in_state_tuition"].min()

df["diferenca"] = df["out_of_state_tuition"] - df["in_state_tuition"]

df

print(df["diferenca"].max())
print(df["diferenca"].min())
print(df["diferenca"].mean())
print(df["diferenca"].median())
busca = df.query("diferenca == 0")
print(len(busca))

#vizualizar graficamente alguns dados de estatistica
df.boxplot(column=["in_state_tuition", "out_of_state_tuition"])

df.hist(column="in_state_tuition", bins=20)