# -*- coding: utf-8 -*-
"""estatistica-correlacao-regressao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e_4Hs8XTldwLhPqC_iL3_t85XjZ225vb
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

df = pd.read_csv("https://drive.google.com/u/1/uc?id=1pygGDM-F4quUo2Jl4ri-vJosb3FkRQNx&export=download")

df

#corr = correlacionar n1: fortemente positivamente correlacionado, n-1 fortemente negativamente correlacionado, n0 fracamente crrelacionado
print(df["Nota"].corr(df["Horas"]))
print(df["Nota"].corr(df["Faltas"]))
print(df["Nota"].corr(df["Chocolate"]))

df2 = pd.read_csv("https://drive.google.com/u/1/uc?id=1ASOWhw5tp-kUbZcIlkg5eCKwZNJt6MwQ&export=download")

df2

print(df2["Prova 1"].corr(df2["Prova 2"]))
print(df2["Prova 1"].corr(df2["Trabalho"]))
print(df2["Prova 2"].corr(df2["Trabalho"]))

plt.plot(df2['Prova 1'],df2['Prova 2'], ".")
(a,b) = np.polyfit(x=df2["Prova 1"], y=df2["Prova 2"], deg=1)
plt.plot(df2["Prova 1"],df2["Prova 2"], ".")
x = np.arange(0,101)
y = a*x+b

plt.plot(x,y,"r")

plt.plot(df2['Prova 1'],df2['Trabalho'], ".")
(a,b) = np.polyfit(x=df2["Prova 1"], y=df2["Trabalho"], deg=1)
plt.plot(df2["Prova 1"],df2["Trabalho"], ".")
x = np.arange(0,101)
y = a*x+b

plt.plot(x,y,"r")

plt.plot(df2['Prova 2'],df2['Trabalho'], ".")
(a,b) = np.polyfit(x=df2["Prova 2"], y=df2["Trabalho"], deg=1)
plt.plot(df2["Prova 2"],df2["Trabalho"], ".")
x = np.arange(0,101)
y = a*x+b

plt.plot(x,y,"r")

plt.plot(df['Horas'],df['Nota'], ".")

#deg expressa uma função de x grau
(a,b) = np.polyfit(x=df["Horas"], y=df["Nota"], deg=1)
print(a)
print(b)

a*15+b

plt.plot(df["Horas"],df["Nota"], ".")
x = np.arange(0,51)
y = a*x+b

plt.plot(x,y,"r")

df3 = pd.read_csv("https://drive.google.com/u/1/uc?id=1TUDYCy8bMLQ--0jRAMXRNsg2hhnQcKGX&export=download")

df3

plt.plot(df3['Cafes'],df3['Nota'], ".")
(a,b,c) = np.polyfit(x=df3["Cafes"], y=df3["Nota"], deg=2)
plt.plot(df3["Cafes"],df3["Nota"], ".")
x = np.arange(0,10,0.2)
y = a*x**2+b*x+c*x
plt.plot(x,y,"r")

plt.plot(df3['Cafes'],df3['Nota'], ".")
grau = int(input())
coeficientes = np.polyfit(x=df3["Cafes"], y=df3["Nota"], deg=grau)
x = np.arange(0,10,0.1)
y = 0*x 
for i in range(0, len(coeficientes)):
  y += coeficientes[i]*x**(grau-i)
plt.plot(x,y,"r")