# -*- coding: utf-8 -*-
"""graficos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WYTlgObNwbly0pZMd4JpiaLjnXIBJPsV
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

plt.plot(1, 2, '.')
plt.plot(3, 4, 'o')

plt.plot([1,2,3],[1,1,0],'.')

listax = []
listay = []

print(listax)
print(listay)


abcissa= float(input("Valor de X: "))
ordenada = float(input("Valor de Y: "))

listax.append(abcissa)
listay.append(ordenada)

print(listax)
print(listay)

plt.plot(listax , listay, '.')

import numpy as np

lista = [10,20,30]

seno= np.sin(lista)
cosseno = np.cos(lista)

print(seno)
print(cosseno)

elementos = np.arange(0, 10, 0.5)
print(elementos)

x = np.arange(-20,20,0.5)
print(x)
y = x*x + 5*x + 5
print(y)
plt.plot(x,y)

import numpy as np

x = np.arange(-10,10,0.5)

y1 = np.sin(x)
y2 = np.cos(x)

plt.plot(x,y1)
plt.plot(x,y2)

import numpy as np

x = np.arange(-10,10,0.01)

y1 = x**3+2*x**2+x+1
y2 = 2*np.sin(x)
y3 = 3*np.cos(x)**2

#plt.plot(x, y1)
plt.plot(x, y2, "b^", label="2sen(x)")
plt.plot(x, y3,"rv",  label="3cos^2(x)")

plt.title("Meu gráfico")
plt.xlabel("Eixo x")
plt.ylabel("Eixo y")
plt.legend()
plt.axis('equal')

