# -*- coding: utf-8 -*-
"""inputs-e-condicionais.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1avMfIV6FBBaOBUDKcvAGHn0JfCxbWu3L
"""

x = float (input("digite o 1 numero: "))
y = float (input("digite o 2 numero: "))
z = float (input("digite o 3 numero: "))

med = (x+y+z)/3
print("a média é: ", med)

idade = int(input("Qual a sua idade? "))
if idade >= 18:
  print("pode beber corote")
else:
  print("beba nescau")

nome = input("Qual é seu nome?")
sobrenome = input ()