# -*- coding: utf-8 -*-
"""inputs-e-condicionais-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RX0tvBOc5g2aeSod9_CyLzhFTRqTy6xi
"""

#Guilherme da Cruz Rodrigues da Silva - 11202231594

anonasc = int(input())
idade = 2022 - anonasc
if idade <= 12:
  print("Voce tem",idade, "anos e, portanto, e crianca.")
elif (idade >= 13) and (idade <= 17):
  print("Voce tem",idade,"anos e, portanto, e adolescente.")
elif (idade >= 18) and (idade <= 64):
  print("Voce tem",idade,"anos e, portanto, e adulto.")
elif idade >= 65:
  print("Voce tem",idade,"anos e, portanto, e experiente.")