# -*- coding: utf-8 -*-
"""teste-math-import.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fRKzhoDbIynQsP0pjUEi6zJ61hovY3Cq
"""

import math
x = input()
if x.isnumeric() == True:
  x = math.factorial(int (x))
  print(x)
elif (x == "ufabc"):
  print("minha universidade")
else:
  print(x)