# -*- coding: utf-8 -*-
"""trabalho6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kXH4hXmruo9cX_xgDOouL61J79oCmyHX
"""

n = int(input())
lista = [0] * n
positives= []
sum = 0
for i in range(n):
  vals= int(input())
  lista[i] += vals
  if lista[i] >= 0:
    positives.append(lista[i])
for l in range(len(positives)):
  sum += positives[l]
positives.reverse()
print(*positives)
print(sum)