# -*- coding: utf-8 -*-
"""trabalho0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YxYQsE9wtgU2iyFZLv9x6vRP82QOJETd
"""

import math
r = 5 
perimc = 2 * math.pi * r
print("perimc = %.2f" % perimc)