# -*- coding: utf-8 -*-
"""trabalho3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LIFsK4FC4vpouYxw1JdTqSO7p_R3T-lp
"""

import numpy as np
F =  input()
R= [ ]
A= float(input()) # Inicio da sequencia
B= float(input()) # fim da sequencia
C= float(input()) # incremento
L = np.arange(A , B , C)
if F == "seno":
  seno = np.sin(L)
  R = seno
elif F == "cosseno":
  cosseno = np.cos(L)
  R = cosseno
elif F == "log10":
  log10 = np.log10(L)
  R = log10
elif F == "log2":
  log2 = np.log2(L)
  R  = log2
else:
  print("funcao desconhecida")
print(*R, sep = ' ')